/* 
	DML - DATA MANIPULATION LANGUAGE
	DDL - DATA DEFINITION LANGUAGE
	DCL - DATA CONTROL LANGUAGE
	TCL - TRANSACTION CONTROL LANGUAGE

*/

/* INSERT */

INSERT INTO CLIENTE VALUES(NULL, 'PAULA', 'M',NULL,'987854625');
INSERT INTO ENDERECO VALUES(NULL,'RJ','NITEROI','RUA JOAQUIM SILVA','ALVORADA',17);

/* FILTROS */

SELECT * FROM CLIENTE
WHERE SEXO = 'M';

/* PAULA COM O SEXO ERRADO */

SELECT * FROM CLIENTE
WHERE IDCLIENTE =17;

UPDATE CLIENTE SET SEXO = 'F' WHERE IDCLIENTE = 17;

/* ALTERADO COM SUCESSO */

/* DELETE */

INSERT INTO CLIENTE VALUES(NULL,'XXX','M',NULL,'XXX');

SELECT * FROM CLIENTE
WHERE IDCLIENTE =18;

DELETE FROM CLIENTE WHERE IDCLIENTE = 18;