Livraria

CREATE DATABASE LIVRARIA;

USE LIVRARIA;

LIVROS
CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(30),
	NOME_AUTOR VARCHAR(40),
	SEXO_AUTOR CHAR(1),
	NUMERO_PAGS INT(8),
	NOME_EDITORA VARCHAR(40),
	VALOR_LIVRO FLOAT(10,2),
	UF_EDITORA VARCHAR(2),
	ANO_PUB INT(4)
);

INSERT INTO LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGS,NOME_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUB) VALUES
('CAVALEIRO REAL', 'ANA CLAUDIA', 'F', 465, 'Atlas', 49.9, 'RJ', 2009);
	
INSERT INTO LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGS,NOME_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUB) VALUES
('SQL para Leigos', 'João Nunes', 'M', 450, 'ADDISON', 98, 'SP', 2018);

INSERT INTO LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGS,NOME_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUB) VALUES
('RECEITAS CASEIRAS', 'CELIA TAVARES', 'F', 210, 'ATLAS', 45, 'RJ', 2008);

INSERT INTO LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGS,NOME_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUB) VALUES
('PESSOAS EFETIVAS', 'EDUARDO SANTOS', 'M', 390, 'BETA', 78.99, 'RJ', 2018);

INSERT INTO LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGS,NOME_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUB) VALUES
('HABITOS SAUDÁVEIS', 'EDUARDOS SANTOS', 'M', 630, 'BETA', 150.98, 'RJ', 2019);

INSERT INTO LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGS,NOME_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUB) VALUES
('A CASA MARROM', 'HERMES MACEDO', 'M', 250, 'BUBBA', 60, 'MG', 2016);

INSERT INTO LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGS,NOME_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUB) VALUES
('ESTACIO QUERIDO', 'GERALDO FRANCISCO', 'M', 310, 'INSIGNIA', 100, 'ES', 2015);

INSERT INTO LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGS,NOME_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUB) VALUES
('PRA SEMPRE AMIGAS', 'LEDA SILVA', 'F', 510, 'INSIGNIA', 78.98, 'ES', 2011);

INSERT INTO LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGS,NOME_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUB) VALUES
('COPAS INESQUECIVEIS', 'MARCO ALCANTARA', 'M', 200, 'LARSON', 130.98, 'RS', 2018);

INSERT INTO LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGS,NOME_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUB) VALUES
('O PODER DA MENTE', 'CLARA MAFRA', 'F', 120, 'CONTINENTAL', 56.58, 'SP', 2017);

/*1*/ 
SELECT * FROM LIVROS;
/*2*/ 
SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS;
/*3*/ 
SELECT NOME_LIVRO, UF_EDITORA FROM LIVROS WHERE SEXO_AUTOR ='M';
/*4*/
SELECT NOME_LIVRO,NUMERO_PAGS FROM LIVROS WHERE SEXO_AUTOR ='F';
/*5*/
SELECT NOME_LIVRO, VALOR_LIVRO FROM LIVROS WHERE UF_EDITORA LIKE 'SP%';
/*6*/
SELECT NOME_AUTOR,SEXO_AUTOR FROM LIVROS WHERE SEXO_AUTOR = 'M' AND UF_EDITORA = 'SP' OR UF_EDITORA = 'RJ';
