
CREATE DATABASE GUIZO; 

USE GUIZO;

CREATE TABLE ALUNOS(
	NUMERO INT,
	NOME VARCHAR(30)
);

DROP DATABASE COMERCIO;
DROP DATABASE EXEMPLO;
DROP DATABASE GUIZO;
DROP DATABASE PROJETO;
DROP DATABASE TESTE;